# -*- coding: utf-8 -*-
"""AI-RESEARCH-COPILOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BpzOq8FfoUoNbJ_xqJamioLQPFTghnU
"""

pip install gradio requests pybtex reportlab nest-asyncio

# ai_research_copilot_hackathon_ui_fixed.py
"""
AI Research Copilot - Hackathon Edition
Enhanced UI, Multi-Citation Styles, Modern Colors
"""

import os
import time
import requests
import nest_asyncio
from typing import List, Dict, Any, Optional
from pybtex.database import BibliographyData, Entry
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
import gradio as gr

nest_asyncio.apply()

# ===================== CONFIG =====================
HF_TOKEN = os.getenv("HF_TOKEN", "").strip() or None
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip() or None
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-70b-versatile")
HF_VERIFY_MODEL = os.getenv("HF_VERIFY_MODEL", "meta-llama/Llama-3.1-70B-Instruct")
SEMANTIC_SCHOLAR_API_KEY = os.getenv("SEMANTIC_SCHOLAR_API_KEY", "").strip() or None
REQUEST_TIMEOUT = 30

# ===================== FUNCTIONS =====================

# Safe getters
def safe_get(d, *keys, default=None):
    try:
        for k in keys:
            if isinstance(d, list) and isinstance(k, int):
                d = d[k]
            else:
                d = d.get(k, {})
        return d if d != {} else default
    except Exception:
        return default

# -------------------- Citation formatting --------------------
def format_authors(authors_list):
    names = []
    for a in authors_list or []:
        if isinstance(a, dict):
            given = a.get("given","")
            family = a.get("family","")
        else:
            given, family = str(a), ""
        if given and family:
            names.append(f"{family}, {given[0]}.")
        elif family:
            names.append(family)
    return ", ".join(names)

def format_citation_apa(item):
    authors = format_authors(item.get("author", item.get("authors", [])))
    year = item.get("issued", {}).get("date-parts", [[item.get("year","")]])[0][0] if item.get("issued") else item.get("year","")
    title = (item.get("title") or [""])[0] if isinstance(item.get("title"), list) else item.get("title","")
    journal = (item.get("container-title") or [""])[0] if item.get("container-title") else item.get("venue","")
    doi = item.get("DOI","") or item.get("doi","")
    if doi:
        return f"{authors} ({year}). {title}. {journal}. https://doi.org/{doi}"
    return f"{authors} ({year}). {title}. {journal}."

def format_citation_ieee(item):
    authors = format_authors(item.get("author", item.get("authors", [])))
    title = (item.get("title") or [""])[0] if isinstance(item.get("title"), list) else item.get("title","")
    journal = (item.get("container-title") or [""])[0] if item.get("container-title") else item.get("venue","")
    year = item.get("issued", {}).get("date-parts", [[item.get("year","")]])[0][0] if item.get("issued") else item.get("year","")
    return f"{authors}, \"{title},\" {journal}, {year}."

def format_citation_mla(item):
    authors = format_authors(item.get("author", item.get("authors", [])))
    title = (item.get("title") or [""])[0] if isinstance(item.get("title"), list) else item.get("title","")
    journal = (item.get("container-title") or [""])[0] if item.get("container-title") else item.get("venue","")
    year = item.get("issued", {}).get("date-parts", [[item.get("year","")]])[0][0] if item.get("issued") else item.get("year","")
    return f"{authors}. \"{title}.\" {journal}, {year}."

def format_citation(item, style="APA"):
    style = style.upper()
    if style == "APA":
        return format_citation_apa(item)
    elif style == "IEEE":
        return format_citation_ieee(item)
    elif style == "MLA":
        return format_citation_mla(item)
    return format_citation_apa(item)

# -------------------- PDF Export --------------------
def export_pdf_clean(out_json: Dict[str,Any], filename: str = "generated_paper.pdf") -> str:
    try:
        doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=40,leftMargin=40, topMargin=40,bottomMargin=40)
        styles = getSampleStyleSheet()
        Story = []
        Story.append(Paragraph(out_json.get("topic","Untitled"), styles["Title"]))
        Story.append(Spacer(1,12))
        Story.append(Paragraph("AI Research Copilot — Generated Draft", styles["Normal"]))
        Story.append(Spacer(1,12))
        for sec in ["abstract","introduction","literature_review","methodology","results","conclusion"]:
            t = out_json.get("sections", {}).get(sec, "")
            if t:
                Story.append(Paragraph(sec.replace("_"," ").title(), styles["Heading2"]))
                Story.append(Paragraph(t.replace("\n","<br/>"), styles["BodyText"]))
                Story.append(Spacer(1,12))
        Story.append(Paragraph("References", styles["Heading2"]))
        for i, r in enumerate(out_json.get("references", []), start=1):
            ref_text = format_citation(r, style="APA")
            Story.append(Paragraph(f"{i}. {ref_text}", styles["BodyText"]))
            Story.append(Spacer(1,6))
        doc.build(Story)
        return filename
    except Exception as e:
        print("PDF export failed:", e)
        return ""

# ===================== UI PIPELINE =====================
def run_ui_pipeline(topic: str, num_refs: int, style: str, use_groq: bool):
    start = time.time()
    if not topic.strip():
        return "Please enter a research topic.", "<div>No references</div>", None, None

    # ===================== USE EXISTING FUNCTIONS =====================
    out_json = generate_full_paper_pipeline(topic, num_refs=num_refs, use_groq=use_groq)

    safe_name = "".join(c for c in topic if c.isalnum() or c in (" ", "_")).strip()[:40].replace(" ", "_") or "paper"
    pdf_path = export_pdf_clean(out_json, filename=f"{safe_name}_generated.pdf")

    bib_path = f"{safe_name}_references.bib"
    try:
        with open(bib_path, "w", encoding="utf-8") as f:
            f.write(out_json.get("bibtex",""))
    except Exception as e:
        print("Failed to write bib file:", e)
        bib_path = None

    # References table
    refs_rows = []
    for i, r in enumerate(out_json.get("references", [])):
        title = (r.get("title") or [""])[0] if isinstance(r.get("title"), list) else r.get("title","")
        authors_list = r.get("author", r.get("authors", []))
        if isinstance(authors_list, list):
            authors_str = ", ".join([f"{a.get('given','')} {a.get('family','')}".strip() for a in authors_list])
        else:
            authors_str = str(authors_list)
        valid = bool(r.get("DOI") or r.get("doi"))
        refs_rows.append({"index": i+1, "title": title, "authors": authors_str, "valid": valid})

    table_html = "<div class='table-container'><table><tr><th>#</th><th>Title</th><th>Authors</th><th>Verified</th></tr>"
    for r in refs_rows:
        check = "✔" if r['valid'] else "—"
        table_html += f"<tr><td>{r['index']}</td><td>{r['title']}</td><td>{r['authors']}</td><td class='center'>{check}</td></tr>"
    table_html += "</table></div>"

    # Sections markdown
    sections_md = f"## {topic}\n\n"
    for sec, text in out_json.get("sections", {}).items():
        sections_md += f"### {sec.replace('_',' ').title()}\n\n{text}\n\n"

    took = time.time() - start
    sections_md += f"\n\n_Generated in {took:.1f}s._"

    return sections_md, table_html, bib_path, pdf_path

# ===================== GRADIO UI =====================
css = """
.gradio-container { font-family:'Arial', sans-serif; background-color:#edf2f7; padding:25px; }
.input-card { padding:25px; background-color:#ffffff; border-radius:15px; box-shadow:0 6px 20px rgba(0,0,0,0.1); margin-bottom:25px; }
.table-container { overflow-x:auto; margin-top:12px; }
.table-container table { width:100%; border-collapse: collapse; font-size:14px; background-color:#fff; }
.table-container th, .table-container td { border:1px solid #ccc; padding:8px; text-align:left; }
.table-container td.center { text-align:center; }
.table-container tr:hover { background-color:#f1f1f1; }
.gr-button { border-radius:10px; font-weight:bold; padding:10px 20px; background-color:#3498db; color:white; border:none; }
.gr-button:hover { background-color:#2980b9; }
"""

with gr.Blocks(css=css, title="AI Research Copilot") as demo:
    with gr.Row():
        with gr.Column(scale=1):
            with gr.Group(elem_classes="input-card"):
                topic_in = gr.Textbox(label="Research Topic", placeholder="e.g. 'AI in Education'")
                refs_in = gr.Slider(label="Number of References", minimum=5, maximum=100, step=5, value=20)
                style_in = gr.Dropdown(choices=['APA','IEEE','MLA'], value='APA', label='Citation Style')
                groq_in = gr.Checkbox(label="Use Groq for generation", value=True)
                run_btn = gr.Button("Generate Paper", variant="primary")

            with gr.Group():
                bib_file = gr.File(label="Download BibTeX", file_types=[".bib"])
                pdf_file = gr.File(label="Download PDF", file_types=[".pdf"])

        with gr.Column(scale=2):
            with gr.Tabs():
                with gr.Tab("Paper Sections"):
                    abstract_md = gr.Markdown()
                with gr.Tab("References Table"):
                    refs_html = gr.HTML()

    run_btn.click(fn=run_ui_pipeline,
                  inputs=[topic_in, refs_in, style_in, groq_in],
                  outputs=[abstract_md, refs_html, bib_file, pdf_file])

if __name__ == "__main__":
    demo.launch(share=True, inbrowser=True)